### ISSUE TITLE
Logo as SVG

### ISSUE THREAD

**Issue by jancborchardt** [sozialhelden/accessibility-cloud#36]
We are in the process of adding accessibility.cloud to http://opensourcediversity.org :)

I could only find the logo as PNG at:
- https://github.com/sozialhelden/accessibility-cloud/blob/master/public/icons/icon-114.png
- https://github.com/sozialhelden/accessibility-cloud/blob/master/public/images/ac-logo-dark.png

(The second one is used on the main page and has some small path/display errors.)

It would be great to have the source SVG so others can use the logo to link to the project in high resolutions or when zoomed. It can also be safely used on the homepage as SVG works in all browsers (except IE8 if you support that, but there can be a fallback for that): https://caniuse.com/#search=svg

**Comment by opyh** [comment]
Hi, thanks for adding the project! :)

Here is a SVG version with some path fixes: https://github.com/sozialhelden/accessibility-cloud/blob/master/public/images/ac-logo-dark.svg

(Credits to @pixtur).
