### ISSUE TITLE
signlanguage?

### ISSUE THREAD

**Issue by cellx** [sozialhelden/accessibility-cloud#46]
How can I find out, if there has provide sign-language or subtitles in different languages too? Maybe somehow to put this in the category 'media' or 'communication'. So the Deaf would know, there is exactly communication accessibility. 

Maybe for hard-of-hearing there is option with 'induction loop'.

**Comment by mutaphysis** [comment]
Hi @cellx, 

you can find these fields in the media subobjects at https://github.com/sozialhelden/accessibility-cloud/blob/270b5c0c78aa9f22f903fb21f0459e7759c7c2d9/docs/exchange-format.md .

For the next generation of the ac-format there is already some more documentation:

https://github.com/sozialhelden/ac-format/blob/master/src/media.ts : 
 - see `Media.hasSubtitles`, `Media. hasRealTimeCaptioning`.
 - The available subtitle languages are a good point, we will make sure to discuss this, right now we only have `Media.languages`.

Hope this helps,
Henrik

**Comment by cellx** [comment]
I still miss the sign-language subobject. That's good to know there should be translate into different sign-language version.

**Comment by mutaphysis** [comment]
Sorry, I am not sure I fully understood your second sentence, could you please rephrase?

In my explanation above I forgot the `Staff.isTrainedInSignage` value, https://github.com/sozialhelden/ac-format/blob/master/src/staff.ts - this should of course also indicate which sign language the staff is able to speak.

From my point of view it definitely makes sense to add a `sign-language` field (probably as an optional array of spoken sign languages) to the media object as well as the induction loop capability.

**Comment by opyh** [comment]
I guess this means that there are different kinds of sign language and we don't indicate in the format yet which one is used. I'd suggest we implement attributes along the naming of `signLanguageCode` and use the proposal from http://www.signwriting.org/archive/docs1/sw0033-Sign-Language-Codes.pdf. What do you think?

**Comment by mutaphysis** [comment]
Looks good, even though its sad that there is no rfc for this yet. The document is nearly 20 years old by now :/

**Comment by opyh** [comment]
I have added `hasInductionLoop` to A11yJSON:

https://github.com/sozialhelden/ac-format/blob/master/src/Accessibility.ts#L71

There is a RFC! For sign language codes, we will support sign language variants. Just use them like any other language code, e.g. inside `media`. We will follow https://tools.ietf.org/html/rfc5646 and its successors for this, so you can use language tags like `ase` or `sgn-ase`.
