### ISSUE TITLE
Wheelmap/OSM source : retrieve data for all kind of disabilities

### ISSUE THREAD

**Issue by PanierAvide** [sozialhelden/accessibility-cloud#48]
Hi AC team,

We're working at I Wheel Share on integrating movie theaters in our chatbot. We have recently added some data into OSM regarding theaters [having equipment for blind people](http://overpass-turbo.eu/s/CUN). But for now, Wheelmap source only retrieve data regarding wheelchair accessibility. Is there any way that Wheelmap source (or another one in AC) offers accessibility data from OSM for all kind of disabilities ?

Regards,

Adrien.

**Comment by holgerd** [comment]
Hi Adrien,
thanks for pointing this out. Due to a refactoring we plan to change the way we sync with OSM in general (we'd like to sync OSM with AC and not Wheelmap). When we do that it would be great to consider other accessibility attributes used in OSM as well!

**Comment by PanierAvide** [comment]
Thanks for your answer. Do you have any idea of when this synchronisation with OSM will be implemented ?

**Comment by holgerd** [comment]
no, sorry

**Comment by PanierAvide** [comment]
OK, thank you for your fast answer :-)

**Comment by opyh** [comment]
Just a little note that we haven't forgotten about this! It's a major task. We're on it, but can't tell a release date yet.

**Comment by PanierAvide** [comment]
Great to hear that, thanks for working on this task :-)

**Comment by opyh** [comment]
While we just got much nearer to this goal in the past 2 month, it will still take some time to finish it. Closing this for now, stay tuned ;)
