### ISSUE TITLE
Can't use Wheelchair api

### ISSUE THREAD

**Issue by katsmunoz** [sozialhelden/accessibility-cloud#74]
Hello everyone!

My name is Katherine Muñoz, I'm from Chile and I'm currently studying programming in Laboratoria. 

Laboratoria it's a bootcamp for women who want to improve their futures in the tech area. During this period, we are faced with new challenges focusing on solving necessities of different users by implementing new technologies. 

In this regard, we are currently working on a project based on using maps from Here to solve problematics of people with reduced mobility, including people in wheelchairs, motor disturbances, physical injuries, elders and pregnant women. For this, our intention is to combine data from your cloud with Here maps, and then, present the best routes according to the users needs. At the same time, we will allow users to comment or post any information they find relevant for other users (for example, if the restaurant they want to go has no access to wheelchairs, they will post a comment about it so other users will know behore hand). 

I signed in in your platform accessibility.cloud, but it said that I needed to be approved first, so I wanted to contact you to let you know about this project and see if this can speed things up. 

Is there any way to use the data from wheelchair map without waiting for verification?

**Comment by opyh** [comment]
Your email is answered!
